name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "brandingheaven/blender-builder"
          install: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: "${{ secrets.DOCKER_USER }}/blender-logo-render:latest"
